"use client";

import { ThemeProvider } from '@material-tailwind/react'
import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from '@/components/navBar/Nav';
import TopBar from '@/components/topBar/TopBar';
import Footer from '@/components/footer/Footer';
import { motion } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <TopBar />
          <Nav />
            {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
